
export const GET_ALL_TASK_SUCCES = "GET_ALL_TASK_SUCCES";
export const GET_ALL_TASK_FAIL = "GET_ALL_TASK_FAIL";


export const GET_ALL_DEPARTMENT_TASK_SUCCES = "GET_ALL_DEPARTMENT_TASK_SUCCES";
export const GET_ALL_DEPARTMENT_TASK_FAIL = "GET_ALL_DEPARTMENT_TASK_FAIL";


export const OPEN = "OPEN";
export const CLOSE = "CLOSE";